"""Keyword templates for the danger detector."""

# Generic danger phrases that refine specific danger types.
GENERIC_DANGER = [
    r"(буде|бути) гучно",
    r"в укриття",
    r"перебувайте в укритті",
    r"будьте обережними",
    r"курс(ом)? на",
    r"{area} увага!",
    r"дві стіни",
    r"2 стіни",
    r"від вікон",
    r"вглиб будівель!",
    r"{area} увага",
    r"{area}.+увага",
    r"{area} зреагувати",
    r"{area} жахне",
    r"на {area}",
    r"на {area}!",
    r"далі {area}",
    r"{area}!!",
    r"{area}!",
    r"❗️{area}!",
    r"🟡{area}!",
    r"🔴🚀.*{area}",
    r"🟡🚀.*{area}",
    r"🔴❗️.*{area}",
    r"🚀.*{area}",
    r"вектор.*{area}",
    r"вектор руху на {area}",
]

# Ballistic-oriented phrases.
BALLISTIC_DANGER = [
    r"балістик",
    r"балістика на {area}",
    r"наближення балістики",
    r"вихід балістики",
    r"вихід бр",
    r"пуск кинджалу",
    r"вихід з бр",
    r"cпуск балістики",
    r"кинджал(?!.*у бік)",
    r"швидкісна ціль",
    r"швидкісна повітряна ціль",
    r"швидкісна у бік {area}",
    r"ціль швидка на {area}",
    r"{area} швидкісна",
    r"{area} є ціл",
    r"{area} ціль",
    r"спуск {area}",
    r"спуск на {area}",
    r"{area} спуск!",
    r"ціль на {area}",
    r"{area} ціль!",
    r"{area} цілі!",
]


# Cruise-missile oriented phrases (including generic "rocket" wording).
CRUISE_DANGER = [
    r"кр на",
    r"кр повз",
    r"кр від",
    r"\bкр\b",
    r"кр {area}",
    r"група кр",
    r"групи кр",
    r"група крилатих",
    r"групи крилатих",
    r"кр через",
    r"підліт кр",
    r"групи ракет",
    r"крилаті ракети",
    r"крилатих ракет",
    r"крилата ракета",
    r"крилаті курсом",
    r"кинджал у бік {area}",
    r"калібр",
    r"крилат[а-яії']*",
    r"ракета заходить",
    r"ракети заходять",
    r"ракети на {area}",
    r"ракета на {area}",
    r"{area} ракета",
    r"ракета {area}",
    r"заходить ракета",
    r"🚀.*?{area}.*?,?\s*йде з",
]

# Drone-oriented phrases.
DRONE_DANGER = [
    r"🛵",
    r"🟡🛵",
    r"заліт",
    r"бпла",
    r"{area} рух!",
    r"маневри",
    r"шахед на {area}",
    r"\d+х {area}",
    r"\d+х.*{area}",
    r"у бік {area}",
    r"в бік {area}",
    r"курс(ом)? на {area}",
    r"{area} йде",
]


__all__ = [
    "BALLISTIC_DANGER",
    "CRUISE_DANGER",
    "DRONE_DANGER",
    "GENERIC_DANGER",
]
